export const fontOptions: {label: string, value: string}[] = [
  { "label": "ABeeZee", "value": "ABeeZee:wght@400" },
  { "label": "Abel", "value": "Abel:wght@400" },
  { "label": "Abhaya Libre Heavy", "value": "Abhaya Libre:wght@800" },
  { "label": "Abhaya Libre", "value": "Abhaya Libre:wght@400;700" },
  { "label": "Acme", "value": "Acme:wght@400" },
  { "label": "Adamina", "value": "Adamina:wght@400" },
  { "label": "Alegreya Heavy", "value": "Alegreya:wght@900" },
  { "label": "Alegreya Sans Extra Light", "value": "Alegreya Sans:wght@100;300" },
  { "label": "Alegreya Sans Heavy", "value": "Alegreya Sans:wght@900" },
  { "label": "Alegreya Sans Light", "value": "Alegreya Sans:wght@300;500" },
  { "label": "Alegreya Sans", "value": "Alegreya Sans:wght@400;700" },
  { "label": "Alegreya", "value": "Alegreya:wght@400;700" },
  { "label": "Aleo", "value": "Aleo:wght@400;700" },
  { "label": "Alice", "value": "Alice:wght@400" },
  { "label": "Alike Angular", "value": "Alike Angular:wght@400" },
  { "label": "Alike", "value": "Alike:wght@400" },
  { "label": "Almarai Heavy", "value": "Almarai:wght@800" },
  { "label": "Almarai", "value": "Almarai:wght@400;700" },
  { "label": "Amiri", "value": "Amiri:wght@400;700" },
  { "label": "Anonymous Pro", "value": "Anonymous Pro:wght@400;700" },
  { "label": "Antic Slab", "value": "Antic Slab:wght@400" },
  { "label": "Anton", "value": "Anton:wght@400" },
  { "label": "Arapey", "value": "Arapey:wght@400" },
  { "label": "Archivo Black", "value": "Archivo Black:wght@400" },
  { "label": "Archivo Extra Light", "value": "Archivo:wght@100;300" },
  { "label": "Archivo Heavy", "value": "Archivo:wght@900" },
  { "label": "Archivo Light", "value": "Archivo:wght@300;500" },
  { "label": "Archivo Narrow", "value": "Archivo Narrow:wght@400;700" },
  { "label": "Archivo", "value": "Archivo:wght@400;700" },
  { "label": "Arial", "value": "Arial" },
  { "label": "Arimo", "value": "Arimo:wght@400;700" },
  { "label": "Arvo", "value": "Arvo:wght@400;700" },
  { "label": "Asap Condensed", "value": "Asap Condensed:wght@400;700" },
  { "label": "Asap", "value": "Asap:wght@400;700" },
  { "label": "Assistant Heavy", "value": "Assistant:wght@800" },
  { "label": "Assistant Light", "value": "Assistant:wght@300;500" },
  { "label": "Assistant", "value": "Assistant:wght@400;700" },
  { "label": "Average", "value": "Average:wght@400" },
  { "label": "Azeret Mono Extra Light", "value": "Azeret Mono:wght@100;300" },
  { "label": "Azeret Mono Heavy", "value": "Azeret Mono:wght@900" },
  { "label": "Azeret Mono Light", "value": "Azeret Mono:wght@300;500" },
  { "label": "Azeret Mono", "value": "Azeret Mono:wght@400;700" },
  { "label": "B612 Mono", "value": "B612 Mono:wght@400;700" },
  { "label": "Barlow Condensed Extra Light", "value": "Barlow Condensed:wght@100;300" },
  { "label": "Barlow Condensed Heavy", "value": "Barlow Condensed:wght@900" },
  { "label": "Barlow Condensed Light", "value": "Barlow Condensed:wght@300;500" },
  { "label": "Barlow Condensed", "value": "Barlow Condensed:wght@400;700" },
  { "label": "Barlow Extra Light", "value": "Barlow:wght@100;300" },
  { "label": "Barlow Heavy", "value": "Barlow:wght@900" },
  { "label": "Barlow Light", "value": "Barlow:wght@300;500" },
  { "label": "Barlow Semi Condensed Extra Light", "value": "Barlow Semi Condensed:wght@100;300" },
  { "label": "Barlow Semi Condensed Heavy", "value": "Barlow Semi Condensed:wght@900" },
  { "label": "Barlow Semi Condensed Light", "value": "Barlow Semi Condensed:wght@300;500" },
  { "label": "Barlow Semi Condensed", "value": "Barlow Semi Condensed:wght@400;700" },
  { "label": "Barlow", "value": "Barlow:wght@400;700" },
  { "label": "Baskervville", "value": "Baskervville:wght@400" },
  { "label": "Belgrano", "value": "Belgrano:wght@400" },
  { "label": "Bitter Extra Light", "value": "Bitter:wght@100;300" },
  { "label": "Bitter Heavy", "value": "Bitter:wght@900" },
  { "label": "Bitter Light", "value": "Bitter:wght@300;500" },
  { "label": "Bitter", "value": "Bitter:wght@400;700" },
  { "label": "Bodoni Moda Heavy", "value": "Bodoni Moda:wght@900" },
  { "label": "Bodoni Moda", "value": "Bodoni Moda:wght@400;700" },
  { "label": "Bree Serif", "value": "Bree Serif:wght@400" },
  { "label": "Cabin", "value": "Cabin:wght@400;700" },
  { "label": "Cairo Heavy", "value": "Cairo:wght@900" },
  { "label": "Cairo Light", "value": "Cairo:wght@300;500" },
  { "label": "Cairo", "value": "Cairo:wght@400;700" },
  { "label": "Cantata One", "value": "Cantata One:wght@400" },
  { "label": "Cardo", "value": "Cardo:wght@400;700" },
  { "label": "Castoro", "value": "Castoro:wght@400" },
  { "label": "Catamaran Extra Light", "value": "Catamaran:wght@100;300" },
  { "label": "Catamaran Heavy", "value": "Catamaran:wght@900" },
  { "label": "Catamaran Light", "value": "Catamaran:wght@300;500" },
  { "label": "Catamaran", "value": "Catamaran:wght@400;700" },
  { "label": "Caudex", "value": "Caudex:wght@400;700" },
  { "label": "Chakra Petch Light", "value": "Chakra Petch:wght@300;500" },
  { "label": "Chakra Petch", "value": "Chakra Petch:wght@400;700" },
  { "label": "Cinzel Heavy", "value": "Cinzel:wght@900" },
  { "label": "Cinzel", "value": "Cinzel:wght@400;700" },
  { "label": "Cormorant Garamond Light", "value": "Cormorant Garamond:wght@300;500" },
  { "label": "Cormorant Garamond", "value": "Cormorant Garamond:wght@400;700" },
  { "label": "Cormorant Light", "value": "Cormorant:wght@300;500" },
  { "label": "Cormorant", "value": "Cormorant:wght@400;700" },
  { "label": "Courier Prime", "value": "Courier Prime:wght@400;700" },
  { "label": "Courier", "value": "Courier" },
  { "label": "Cousine", "value": "Cousine:wght@400;700" },
  { "label": "Crete Round", "value": "Crete Round:wght@400" },
  { "label": "Crimson Pro Heavy", "value": "Crimson Pro:wght@900" },
  { "label": "Crimson Pro Light", "value": "Crimson Pro:wght@300;500" },
  { "label": "Crimson Pro", "value": "Crimson Pro:wght@400;700" },
  { "label": "Cutive Mono", "value": "Cutive Mono:wght@400" },
  { "label": "Didact Gothic", "value": "Didact Gothic:wght@400" },
  { "label": "DM Mono Light", "value": "DM Mono:wght@300;500" },
  { "label": "DM Mono", "value": "DM Mono:wght@400" },
  { "label": "DM Sans", "value": "DM Sans:wght@400;700" },
  { "label": "DM Serif Display", "value": "DM Serif Display:wght@400" },
  { "label": "DM Serif Text", "value": "DM Serif Text:wght@400" },
  { "label": "Domine", "value": "Domine:wght@400;700" },
  { "label": "Dosis Heavy", "value": "Dosis:wght@800" },
  { "label": "Dosis Light", "value": "Dosis:wght@300;500" },
  { "label": "Dosis", "value": "Dosis:wght@400;700" },
  { "label": "EB Garamond Heavy", "value": "EB Garamond:wght@800" },
  { "label": "EB Garamond", "value": "EB Garamond:wght@400;700" },
  { "label": "Eczar Heavy", "value": "Eczar:wght@800" },
  { "label": "Eczar", "value": "Eczar:wght@400;700" },
  { "label": "Enriqueta", "value": "Enriqueta:wght@400;700" },
  { "label": "Exo 2 Extra Light", "value": "Exo 2:wght@100;300" },
  { "label": "Exo 2 Heavy", "value": "Exo 2:wght@900" },
  { "label": "Exo 2 Light", "value": "Exo 2:wght@300;500" },
  { "label": "Exo 2", "value": "Exo 2:wght@400;700" },
  { "label": "Exo Extra Light", "value": "Exo:wght@100;300" },
  { "label": "Exo Heavy", "value": "Exo:wght@900" },
  { "label": "Exo Light", "value": "Exo:wght@300;500" },
  { "label": "Exo", "value": "Exo:wght@400;700" },
  { "label": "Faustina Heavy", "value": "Faustina:wght@800" },
  { "label": "Faustina Light", "value": "Faustina:wght@300;500" },
  { "label": "Faustina", "value": "Faustina:wght@400;700" },
  { "label": "Fira Code Light", "value": "Fira Code:wght@300;500" },
  { "label": "Fira Code", "value": "Fira Code:wght@400;700" },
  { "label": "Fira Mono", "value": "Fira Mono:wght@400;700" },
  { "label": "Fira Sans Condensed Extra Light", "value": "Fira Sans Condensed:wght@100;300" },
  { "label": "Fira Sans Condensed Heavy", "value": "Fira Sans Condensed:wght@900" },
  { "label": "Fira Sans Condensed Light", "value": "Fira Sans Condensed:wght@300;500" },
  { "label": "Fira Sans Condensed", "value": "Fira Sans Condensed:wght@400;700" },
  { "label": "Fira Sans Extra Light", "value": "Fira Sans:wght@100;300" },
  { "label": "Fira Sans Heavy", "value": "Fira Sans:wght@900" },
  { "label": "Fira Sans Light", "value": "Fira Sans:wght@300;500" },
  { "label": "Fira Sans", "value": "Fira Sans:wght@400;700" },
  { "label": "Fjalla One", "value": "Fjalla One:wght@400" },
  { "label": "Francois One", "value": "Francois One:wght@400" },
  { "label": "Frank Ruhl Libre Heavy", "value": "Frank Ruhl Libre:wght@900" },
  { "label": "Frank Ruhl Libre Light", "value": "Frank Ruhl Libre:wght@300;500" },
  { "label": "Frank Ruhl Libre", "value": "Frank Ruhl Libre:wght@400;700" },
  { "label": "Gelasio", "value": "Gelasio:wght@400;700" },
  { "label": "Geneva", "value": "Geneva" },
  { "label": "Gentium Basic", "value": "Gentium Basic:wght@400;700" },
  { "label": "Gentium Book Basic", "value": "Gentium Book Basic:wght@400;700" },
  { "label": "Georgia", "value": "Georgia" },
  { "label": "GFS Didot", "value": "GFS Didot:wght@400" },
  { "label": "Gilda Display", "value": "Gilda Display:wght@400" },
  { "label": "Glegoo", "value": "Glegoo:wght@400;700" },
  { "label": "Heebo Extra Light", "value": "Heebo:wght@100;300" },
  { "label": "Heebo Heavy", "value": "Heebo:wght@900" },
  { "label": "Heebo Light", "value": "Heebo:wght@300;500" },
  { "label": "Heebo", "value": "Heebo:wght@400;700" },
  { "label": "Helvetica", "value": "Helvetica" },
  { "label": "Hind Light", "value": "Hind:wght@300;500" },
  { "label": "Hind Madurai Light", "value": "Hind Madurai:wght@300;500" },
  { "label": "Hind Madurai", "value": "Hind Madurai:wght@400;700" },
  { "label": "Hind Siliguri Light", "value": "Hind Siliguri:wght@300;500" },
  { "label": "Hind Siliguri", "value": "Hind Siliguri:wght@400;700" },
  { "label": "Hind", "value": "Hind:wght@400;700" },
  { "label": "Holtwood One SC", "value": "Holtwood One SC:wght@400" },
  { "label": "IBM Plex Mono Extra Light", "value": "IBM Plex Mono:wght@100;300" },
  { "label": "IBM Plex Mono Light", "value": "IBM Plex Mono:wght@300;500" },
  { "label": "IBM Plex Mono", "value": "IBM Plex Mono:wght@400;700" },
  { "label": "IBM Plex Sans Extra Light", "value": "IBM Plex Sans:wght@100;300" },
  { "label": "IBM Plex Sans Light", "value": "IBM Plex Sans:wght@300;500" },
  { "label": "IBM Plex Sans", "value": "IBM Plex Sans:wght@400;700" },
  { "label": "IBM Plex Serif Extra Light", "value": "IBM Plex Serif:wght@100;300" },
  { "label": "IBM Plex Serif Light", "value": "IBM Plex Serif:wght@300;500" },
  { "label": "IBM Plex Serif", "value": "IBM Plex Serif:wght@400;700" },
  { "label": "IM Fell English SC", "value": "IM Fell English SC:wght@400" },
  { "label": "Impact", "value": "Impact" },
  { "label": "Inconsolata Heavy", "value": "Inconsolata:wght@900" },
  { "label": "Inconsolata Light", "value": "Inconsolata:wght@300;500" },
  { "label": "Inconsolata", "value": "Inconsolata:wght@400;700" },
  { "label": "Inter Extra Light", "value": "Inter:wght@100;300" },
  { "label": "Inter Heavy", "value": "Inter:wght@900" },
  { "label": "Inter Light", "value": "Inter:wght@300;500" },
  { "label": "Inter", "value": "Inter:wght@400;700" },
  { "label": "JetBrains Mono Extra Light", "value": "JetBrains Mono:wght@100;300" },
  { "label": "JetBrains Mono Heavy", "value": "JetBrains Mono:wght@800" },
  { "label": "JetBrains Mono Light", "value": "JetBrains Mono:wght@300;500" },
  { "label": "JetBrains Mono", "value": "JetBrains Mono:wght@400;700" },
  { "label": "Josefin Sans Extra Light", "value": "Josefin Sans:wght@100;300" },
  { "label": "Josefin Sans Light", "value": "Josefin Sans:wght@300;500" },
  { "label": "Josefin Sans", "value": "Josefin Sans:wght@400;700" },
  { "label": "Josefin Slab Extra Light", "value": "Josefin Slab:wght@100;300" },
  { "label": "Josefin Slab Light", "value": "Josefin Slab:wght@300;500" },
  { "label": "Josefin Slab", "value": "Josefin Slab:wght@400;700" },
  { "label": "Jost Extra Light", "value": "Jost:wght@100;300" },
  { "label": "Jost Heavy", "value": "Jost:wght@900" },
  { "label": "Jost Light", "value": "Jost:wght@300;500" },
  { "label": "Jost", "value": "Jost:wght@400;700" },
  { "label": "Judson", "value": "Judson:wght@400;700" },
  { "label": "Kameron", "value": "Kameron:wght@400;700" },
  { "label": "Kanit Extra Light", "value": "Kanit:wght@100;300" },
  { "label": "Kanit Heavy", "value": "Kanit:wght@900" },
  { "label": "Kanit Light", "value": "Kanit:wght@300;500" },
  { "label": "Kanit", "value": "Kanit:wght@400;700" },
  { "label": "Karla Heavy", "value": "Karla:wght@800" },
  { "label": "Karla Light", "value": "Karla:wght@300;500" },
  { "label": "Karla", "value": "Karla:wght@400;700" },
  { "label": "Karma Light", "value": "Karma:wght@300;500" },
  { "label": "Karma", "value": "Karma:wght@400;700" },
  { "label": "Kreon Light", "value": "Kreon:wght@300;500" },
  { "label": "Kreon", "value": "Kreon:wght@400;700" },
  { "label": "Lato Extra Light", "value": "Lato:wght@100;300" },
  { "label": "Lato Heavy", "value": "Lato:wght@900" },
  { "label": "Lato", "value": "Lato:wght@400;700" },
  { "label": "Libre Baskerville", "value": "Libre Baskerville:wght@400;700" },
  { "label": "Libre Caslon Text", "value": "Libre Caslon Text:wght@400;700" },
  { "label": "Libre Franklin Extra Light", "value": "Libre Franklin:wght@100;300" },
  { "label": "Libre Franklin Heavy", "value": "Libre Franklin:wght@900" },
  { "label": "Libre Franklin Light", "value": "Libre Franklin:wght@300;500" },
  { "label": "Libre Franklin", "value": "Libre Franklin:wght@400;700" },
  { "label": "Literata Heavy", "value": "Literata:wght@900" },
  { "label": "Literata Light", "value": "Literata:wght@300;500" },
  { "label": "Literata", "value": "Literata:wght@400;700" },
  { "label": "Lora", "value": "Lora:wght@400;700" },
  { "label": "Lucia Console", "value": "Lucia Console" },
  { "label": "Lucida Grande", "value": "Lucida Grande" },
  { "label": "Lusitana", "value": "Lusitana:wght@400;700" },
  { "label": "M PLUS 1p Extra Light", "value": "M PLUS 1p:wght@100;300" },
  { "label": "M PLUS 1p Heavy", "value": "M PLUS 1p:wght@900" },
  { "label": "M PLUS 1p Light", "value": "M PLUS 1p:wght@300;500" },
  { "label": "M PLUS 1p", "value": "M PLUS 1p:wght@400;700" },
  { "label": "M PLUS Rounded 1c Extra Light", "value": "M PLUS Rounded 1c:wght@100;300" },
  { "label": "M PLUS Rounded 1c Heavy", "value": "M PLUS Rounded 1c:wght@900" },
  { "label": "M PLUS Rounded 1c Light", "value": "M PLUS Rounded 1c:wght@300;500" },
  { "label": "M PLUS Rounded 1c", "value": "M PLUS Rounded 1c:wght@400;700" },
  { "label": "Major Mono Display", "value": "Major Mono Display:wght@400" },
  { "label": "Manrope Heavy", "value": "Manrope:wght@800" },
  { "label": "Manrope Light", "value": "Manrope:wght@300;500" },
  { "label": "Manrope", "value": "Manrope:wght@400;700" },
  { "label": "Marcellus SC", "value": "Marcellus SC:wght@400" },
  { "label": "Marcellus", "value": "Marcellus:wght@400" },
  { "label": "Markazi Text", "value": "Markazi Text:wght@400;700" },
  { "label": "Martel Heavy", "value": "Martel:wght@900" },
  { "label": "Martel", "value": "Martel:wght@400;700" },
  { "label": "Mate SC", "value": "Mate SC:wght@400" },
  { "label": "Mate", "value": "Mate:wght@400" },
  { "label": "Maven Pro Heavy", "value": "Maven Pro:wght@900" },
  { "label": "Maven Pro", "value": "Maven Pro:wght@400;700" },
  { "label": "Merriweather Heavy", "value": "Merriweather:wght@900" },
  { "label": "Merriweather Sans Heavy", "value": "Merriweather Sans:wght@800" },
  { "label": "Merriweather Sans Light", "value": "Merriweather Sans:wght@300;500" },
  { "label": "Merriweather Sans", "value": "Merriweather Sans:wght@400;700" },
  { "label": "Merriweather", "value": "Merriweather:wght@400;700" },
  { "label": "Monaco", "value": "Monaco" },
  { "label": "Monda", "value": "Monda:wght@400;700" },
  { "label": "Montserrat Extra Light", "value": "Montserrat:wght@100;300" },
  { "label": "Montserrat Heavy", "value": "Montserrat:wght@900" },
  { "label": "Montserrat Light", "value": "Montserrat:wght@300;500" },
  { "label": "Montserrat", "value": "Montserrat:wght@400;700" },
  { "label": "Mukta Heavy", "value": "Mukta:wght@800" },
  { "label": "Mukta Light", "value": "Mukta:wght@300;500" },
  { "label": "Mukta", "value": "Mukta:wght@400;700" },
  { "label": "Mulish Heavy", "value": "Mulish:wght@900" },
  { "label": "Mulish Light", "value": "Mulish:wght@300;500" },
  { "label": "Mulish", "value": "Mulish:wght@400;700" },
  { "label": "Nanum Gothic Coding", "value": "Nanum Gothic Coding:wght@400;700" },
  { "label": "Nanum Gothic Heavy", "value": "Nanum Gothic:wght@800" },
  { "label": "Nanum Gothic", "value": "Nanum Gothic:wght@400;700" },
  { "label": "Nanum Myeongjo Heavy", "value": "Nanum Myeongjo:wght@800" },
  { "label": "Nanum Myeongjo", "value": "Nanum Myeongjo:wght@400;700" },
  { "label": "Neuton Heavy", "value": "Neuton:wght@800" },
  { "label": "Neuton", "value": "Neuton:wght@400;700" },
  { "label": "Noticia Text", "value": "Noticia Text:wght@400;700" },
  { "label": "Nova Mono", "value": "Nova Mono:wght@400" },
  { "label": "Nunito Heavy", "value": "Nunito:wght@900" },
  { "label": "Nunito Light", "value": "Nunito:wght@300;500" },
  { "label": "Nunito Sans Heavy", "value": "Nunito Sans:wght@900" },
  { "label": "Nunito Sans", "value": "Nunito Sans:wght@400;700" },
  { "label": "Nunito", "value": "Nunito:wght@400;700" },
  { "label": "Old Standard TT", "value": "Old Standard TT:wght@400;700" },
  { "label": "Open Sans Heavy", "value": "Open Sans:wght@800" },
  { "label": "Open Sans Light", "value": "Open Sans:wght@300;500" },
  { "label": "Open Sans", "value": "Open Sans:wght@400;700" },
  { "label": "Orbitron Heavy", "value": "Orbitron:wght@900" },
  { "label": "Orbitron", "value": "Orbitron:wght@400;700" },
  { "label": "Oswald Light", "value": "Oswald:wght@300;500" },
  { "label": "Oswald", "value": "Oswald:wght@400;700" },
  { "label": "Overpass Extra Light", "value": "Overpass:wght@100;300" },
  { "label": "Overpass Heavy", "value": "Overpass:wght@900" },
  { "label": "Overpass Light", "value": "Overpass:wght@300;500" },
  { "label": "Overpass Mono Light", "value": "Overpass Mono:wght@300;500" },
  { "label": "Overpass Mono", "value": "Overpass Mono:wght@400;700" },
  { "label": "Overpass", "value": "Overpass:wght@400;700" },
  { "label": "Oxygen Mono", "value": "Oxygen Mono:wght@400" },
  { "label": "Oxygen", "value": "Oxygen:wght@400;700" },
  { "label": "Padauk", "value": "Padauk:wght@400;700" },
  { "label": "Palatino", "value": "Palatino" },
  { "label": "Paytone One", "value": "Paytone One:wght@400" },
  { "label": "Play", "value": "Play:wght@400;700" },
  { "label": "Playfair Display Heavy", "value": "Playfair Display:wght@900" },
  { "label": "Playfair Display SC Heavy", "value": "Playfair Display SC:wght@900" },
  { "label": "Playfair Display SC", "value": "Playfair Display SC:wght@400;700" },
  { "label": "Playfair Display", "value": "Playfair Display:wght@400;700" },
  { "label": "Poppins Extra Light", "value": "Poppins:wght@100;300" },
  { "label": "Poppins Heavy", "value": "Poppins:wght@900" },
  { "label": "Poppins Light", "value": "Poppins:wght@300;500" },
  { "label": "Poppins", "value": "Poppins:wght@400;700" },
  { "label": "Prata", "value": "Prata:wght@400" },
  { "label": "Pridi Light", "value": "Pridi:wght@300;500" },
  { "label": "Pridi", "value": "Pridi:wght@400;700" },
  { "label": "Prompt Extra Light", "value": "Prompt:wght@100;300" },
  { "label": "Prompt Heavy", "value": "Prompt:wght@900" },
  { "label": "Prompt Light", "value": "Prompt:wght@300;500" },
  { "label": "Prompt", "value": "Prompt:wght@400;700" },
  { "label": "PT Mono", "value": "PT Mono:wght@400" },
  { "label": "PT Sans Caption", "value": "PT Sans Caption:wght@400;700" },
  { "label": "PT Sans Narrow", "value": "PT Sans Narrow:wght@400;700" },
  { "label": "PT Sans", "value": "PT Sans:wght@400;700" },
  { "label": "PT Serif Caption", "value": "PT Serif Caption:wght@400" },
  { "label": "PT Serif", "value": "PT Serif:wght@400;700" },
  { "label": "Public Sans Extra Light", "value": "Public Sans:wght@100;300" },
  { "label": "Public Sans Heavy", "value": "Public Sans:wght@900" },
  { "label": "Public Sans Light", "value": "Public Sans:wght@300;500" },
  { "label": "Public Sans", "value": "Public Sans:wght@400;700" },
  { "label": "Quattrocento", "value": "Quattrocento:wght@400;700" },
  { "label": "Questrial", "value": "Questrial:wght@400" },
  { "label": "Quicksand Light", "value": "Quicksand:wght@300;500" },
  { "label": "Quicksand", "value": "Quicksand:wght@400;700" },
  { "label": "Rajdhani Light", "value": "Rajdhani:wght@300;500" },
  { "label": "Rajdhani", "value": "Rajdhani:wght@400;700" },
  { "label": "Raleway Extra Light", "value": "Raleway:wght@100;300" },
  { "label": "Raleway Heavy", "value": "Raleway:wght@900" },
  { "label": "Raleway Light", "value": "Raleway:wght@300;500" },
  { "label": "Raleway", "value": "Raleway:wght@400;700" },
  { "label": "Red Hat Display Heavy", "value": "Red Hat Display:wght@900" },
  { "label": "Red Hat Display Light", "value": "Red Hat Display:wght@300;500" },
  { "label": "Red Hat Display", "value": "Red Hat Display:wght@400;700" },
  { "label": "Red Hat Mono Light", "value": "Red Hat Mono:wght@300;500" },
  { "label": "Red Hat Mono", "value": "Red Hat Mono:wght@400;700" },
  { "label": "Roboto Condensed", "value": "Roboto Condensed:wght@400;700" },
  { "label": "Roboto Extra Light", "value": "Roboto:wght@100;300" },
  { "label": "Roboto Heavy", "value": "Roboto:wght@900" },
  { "label": "Roboto Light", "value": "Roboto:wght@300;500" },
  { "label": "Roboto Mono Extra Light", "value": "Roboto Mono:wght@100;300" },
  { "label": "Roboto Mono Light", "value": "Roboto Mono:wght@300;500" },
  { "label": "Roboto Mono", "value": "Roboto Mono:wght@400;700" },
  { "label": "Roboto Slab Extra Light", "value": "Roboto Slab:wght@100;300" },
  { "label": "Roboto Slab Heavy", "value": "Roboto Slab:wght@900" },
  { "label": "Roboto Slab Light", "value": "Roboto Slab:wght@300;500" },
  { "label": "Roboto Slab", "value": "Roboto Slab:wght@400;700" },
  { "label": "Roboto", "value": "Roboto:wght@400;700" },
  { "label": "Rokkitt Extra Light", "value": "Rokkitt:wght@100;300" },
  { "label": "Rokkitt Heavy", "value": "Rokkitt:wght@900" },
  { "label": "Rokkitt Light", "value": "Rokkitt:wght@300;500" },
  { "label": "Rokkitt", "value": "Rokkitt:wght@400;700" },
  { "label": "Rozha One", "value": "Rozha One:wght@400" },
  { "label": "Rubik Heavy", "value": "Rubik:wght@900" },
  { "label": "Rubik Light", "value": "Rubik:wght@300;500" },
  { "label": "Rubik", "value": "Rubik:wght@400;700" },
  { "label": "Rufina", "value": "Rufina:wght@400;700" },
  { "label": "Russo One", "value": "Russo One:wght@400" },
  { "label": "Saira Condensed Extra Light", "value": "Saira Condensed:wght@100;300" },
  { "label": "Saira Condensed Heavy", "value": "Saira Condensed:wght@900" },
  { "label": "Saira Condensed Light", "value": "Saira Condensed:wght@300;500" },
  { "label": "Saira Condensed", "value": "Saira Condensed:wght@400;700" },
  { "label": "Sanchez", "value": "Sanchez:wght@400" },
  { "label": "Sarabun Extra Light", "value": "Sarabun:wght@100;300" },
  { "label": "Sarabun Heavy", "value": "Sarabun:wght@800" },
  { "label": "Sarabun Light", "value": "Sarabun:wght@300;500" },
  { "label": "Sarabun", "value": "Sarabun:wght@400;700" },
  { "label": "Sawarabi Mincho", "value": "Sawarabi Mincho:wght@400" },
  { "label": "Secular One", "value": "Secular One:wght@400" },
  { "label": "Share Tech Mono", "value": "Share Tech Mono:wght@400" },
  { "label": "Signika Light", "value": "Signika:wght@300;500" },
  { "label": "Signika Negative Light", "value": "Signika Negative:wght@300;500" },
  { "label": "Signika Negative", "value": "Signika Negative:wght@400;700" },
  { "label": "Signika", "value": "Signika:wght@400;700" },
  { "label": "Slabo 27px", "value": "Slabo 27px:wght@400" },
  { "label": "Sorts Mill Goudy", "value": "Sorts Mill Goudy:wght@400" },
  { "label": "Source Code Pro Heavy", "value": "Source Code Pro:wght@900" },
  { "label": "Source Code Pro Light", "value": "Source Code Pro:wght@300;500" },
  { "label": "Source Code Pro", "value": "Source Code Pro:wght@400;700" },
  { "label": "Source Sans Pro Heavy", "value": "Source Sans Pro:wght@900" },
  { "label": "Source Sans Pro", "value": "Source Sans Pro:wght@400;700" },
  { "label": "Source Serif 4 Heavy", "value": "Source Serif 4:wght@900" },
  { "label": "Source Serif 4 Light", "value": "Source Serif 4:wght@300;500" },
  { "label": "Source Serif 4", "value": "Source Serif 4:wght@400;700" },
  { "label": "Source Serif Pro Heavy", "value": "Source Serif Pro:wght@900" },
  { "label": "Source Serif Pro", "value": "Source Serif Pro:wght@400;700" },
  { "label": "Space Grotesk Light", "value": "Space Grotesk:wght@300;500" },
  { "label": "Space Grotesk", "value": "Space Grotesk:wght@400;700" },
  { "label": "Space Mono", "value": "Space Mono:wght@400;700" },
  { "label": "Spectral Heavy", "value": "Spectral:wght@800" },
  { "label": "Spectral Light", "value": "Spectral:wght@300;500" },
  { "label": "Spectral", "value": "Spectral:wght@400;700" },
  { "label": "Suez One", "value": "Suez One:wght@400" },
  { "label": "Suisse Intl", "value": "Suisse Intl" },
  { "label": "Syne Mono", "value": "Syne Mono:wght@400" },
  { "label": "Tahoma", "value": "Tahoma" },
  { "label": "Tajawal Heavy", "value": "Tajawal:wght@900" },
  { "label": "Tajawal Light", "value": "Tajawal:wght@300;500" },
  { "label": "Tajawal", "value": "Tajawal:wght@400;700" },
  { "label": "Taviraj Extra Light", "value": "Taviraj:wght@100;300" },
  { "label": "Taviraj Heavy", "value": "Taviraj:wght@900" },
  { "label": "Taviraj Light", "value": "Taviraj:wght@300;500" },
  { "label": "Taviraj", "value": "Taviraj:wght@400;700" },
  { "label": "Teko Light", "value": "Teko:wght@300;500" },
  { "label": "Teko", "value": "Teko:wght@400;700" },
  { "label": "Times New Roman", "value": "Times New Roman" },
  { "label": "Tinos", "value": "Tinos:wght@400;700" },
  { "label": "Titillium Web Heavy", "value": "Titillium Web:wght@900" },
  { "label": "Titillium Web", "value": "Titillium Web:wght@400;700" },
  { "label": "Ubuntu Condensed", "value": "Ubuntu Condensed:wght@400" },
  { "label": "Ubuntu Light", "value": "Ubuntu:wght@300;500" },
  { "label": "Ubuntu Mono", "value": "Ubuntu Mono:wght@400;700" },
  { "label": "Ubuntu", "value": "Ubuntu:wght@400;700" },
  { "label": "Ultra", "value": "Ultra:wght@400" },
  { "label": "Unna", "value": "Unna:wght@400;700" },
  { "label": "Varela Round", "value": "Varela Round:wght@400" },
  { "label": "Verdana", "value": "Verdana" },
  { "label": "Vidaloka", "value": "Vidaloka:wght@400" },
  { "label": "Volkhov", "value": "Volkhov:wght@400;700" },
  { "label": "Vollkorn Heavy", "value": "Vollkorn:wght@900" },
  { "label": "Vollkorn", "value": "Vollkorn:wght@400;700" },
  { "label": "VT323", "value": "VT323:wght@400" },
  { "label": "Work Sans Extra Light", "value": "Work Sans:wght@100;300" },
  { "label": "Work Sans Heavy", "value": "Work Sans:wght@900" },
  { "label": "Work Sans Light", "value": "Work Sans:wght@300;500" },
  { "label": "Work Sans", "value": "Work Sans:wght@400;700" },
  { "label": "Xanh Mono", "value": "Xanh Mono:wght@400" },
  { "label": "Yanone Kaffeesatz Light", "value": "Yanone Kaffeesatz:wght@300;500" },
  { "label": "Yanone Kaffeesatz", "value": "Yanone Kaffeesatz:wght@400;700" },
  { "label": "Yantramanav Extra Light", "value": "Yantramanav:wght@100;300" },
  { "label": "Yantramanav Heavy", "value": "Yantramanav:wght@900" },
  { "label": "Yantramanav Light", "value": "Yantramanav:wght@300;500" },
  { "label": "Yantramanav", "value": "Yantramanav:wght@400;700" },
  { "label": "Yrsa Light", "value": "Yrsa:wght@300;500" },
  { "label": "Yrsa", "value": "Yrsa:wght@400;700" },
  { "label": "Zilla Slab Light", "value": "Zilla Slab:wght@300;500" },
  { "label": "Zilla Slab", "value": "Zilla Slab:wght@400;700" }
]
