fragment LayoutQueryFragment on Query {
  getGlobalDocument(relativePath: "index.json") {
    data {
      siteUrl
      favicon
      gtmId
      desktopWidth
      redirects {
        from
        to
      }
      colors {
        primary
        accent1
        accent2
        accent3
        accent4
        white
        grayLight
        gray
        grayDark
        black
      }
      fonts {
        font1
        font2
        font3
        font4
      }
      sizeLeading {
        textXs
        textSm
        textMd
        textLg
        textXl
        text2xl
        text3xl
        text4xl
        text5xl
        text6xl
        text7xl
        text8xl
      }
      buttons {
        primaryFill
        primaryTypography
        primaryBorder
        primaryPadding
        primaryRounded
        secondaryFill
        secondaryTypography
        secondaryBorder
        secondaryPadding
        secondaryRounded
        minorFill
        minorTypography
        minorBorder
        minorPadding
        minorRounded
      }
      logo {
        logoType
        logoTypeStyle
        image
        imageWidth
        imageHeight
        imageMargin
      }
      nav {
        navItems {
          link
          label
        }
        navAlignment
        navTypeStyle
        navBackgroundColor
        padding
      }
      blocks {
        __typename
        ... on GlobalBlocksPhotoCards {
          background {
            fillStyles
            src
            position
            ornaments {
              src
              alignment
              width
              height
              xOffset
              yOffset
            }
          }
          label
          headline
          subhead
          body
          buttons {
            label
            type
            link
          }
          items {
            image {
              src
              alt
            }
            label
            headline
            subhead
            text
            link
            buttonLabel
          }
          style {
            minHeight
            columns
            textAlignment
            padding
            labelStyles
            headlineStyles
            subheadStyles
            textStyles
            contentOrder
            contentWidth
          }
          cardStyle {
            type
            padding
            buttonType
            imageStyles
            labelStyles
            headlineStyles
            subheadStyles
            textStyles
            fillStyles
          }
          navigationLabel
        }
        ... on GlobalBlocksTextCards {
          background {
            fillStyles
            src
            position
            ornaments {
              src
              alignment
              width
              height
              xOffset
              yOffset
            }
          }  
          label
          headline
          subhead
          body
          buttons {
            label
            type
            link
          }
          items {
            headline
            subhead
            text
            link
            buttonLabel
          }
          style {
            minHeight
            columns
            textAlignment
            padding
            labelStyles
            headlineStyles
            subheadStyles
            textStyles
            contentOrder
            contentWidth
          }
          cardStyle {
            type
            padding
            borderStyles
            buttonType
            labelStyles
            headlineStyles
            subheadStyles
            textStyles
            fillStyles
          }
          navigationLabel
        }
        ... on GlobalBlocksFeature {
          image {
            src
            alt
          }
          background {
            fillStyles
            src
            position
            ornaments {
              src
              alignment
              width
              height
              xOffset
              yOffset
            }
          }        
          label
          headline
          subhead
          body
          buttons {
            label
            type
            link
          }
          style {
            alignment
            featureContent
            featureImage
            imagePadding
            padding
            contentOrder
            labelStyles
            headlineStyles
            subheadStyles
            textStyles
          }
          navigationLabel
        }
        ... on GlobalBlocksBanner {
          image {
            src
            alt
          }
          background {
            fillStyles
            src
            position
            ornaments {
              src
              alignment
              width
              height
              xOffset
              yOffset
            }
          }
          label
          headline
          subhead
          body
          buttons {
            label
            link
            type
            type
          }
          style {
            minHeight
            width
            padding
            labelStyles
            headlineStyles
            subheadStyles
            textStyles
            textAlignment
            contentOrder
          }
          navigationLabel
        }
        ... on GlobalBlocksEmbed {
          background {
            fillStyles
            src
            position
            ornaments {
              src
              alignment
              width
              height
              xOffset
              yOffset
            }
          }
          markup
          style {
            minHeight
            fullWidth
            padding
          }
          navigationLabel
        }
        ... on GlobalBlocksTailwindFeature {
           tailwind {
            section
            wrap
            imageWrap
            image
            contentWrap
            content
            label
            headline
            subhead
            text
            buttons
            button
          }
          image {
            src
            alt
          }
          background {
            fillStyles
            src
            position
            ornaments {
              src
              alignment
              width
              height
              xOffset
              yOffset
            }
          }
          label
          headline
          subhead
          body
          buttons {
            label
            link
          }
          navigationLabel
        }
        ... on GlobalBlocksTailwindCards {
           tailwind {
            section
            wrap
            imageWrap
            image
            contentWrap
            content
            label
            headline
            subhead
            text
            buttons
            button
            cardLabel
            cardHeadline
            cardSubhead
            cardText
            cardButtons
            cardButton
          }
          image {
            src
            alt
          }
          background {
            fillStyles
            src
            position
            ornaments {
              src
              alignment
              width
              height
              xOffset
              yOffset
            }
          }
          label
          headline
          subhead
          body
          buttons {
            label
            link
          }
          items {
            image {
              src
              alt
            }
            label
            headline
            subhead
            text
            link
            buttonLabel
          }
          navigationLabel
        }
      }
    }
  }
}
