query pageQuery {
  ...LayoutQueryFragment
  postConnection {
    edges {
      node {
        id
        _values
        _sys {
          filename
        }
      }
    }
  },
  eventConnection {
    edges {
      node {
        id
        _values
        _sys {
          filename
        }
      }
    }
  }
}

query contentQuery($relativePath: String!) {
  ...LayoutQueryFragment
  page(relativePath: $relativePath) {
    ...PageParts
  }
}

query blogPostQuery($relativePath: String!) {
  ...LayoutQueryFragment
  post(relativePath: $relativePath) {
    ...PostParts
  }
}

query eventQuery($relativePath: String!) {
  ...LayoutQueryFragment
  event(relativePath: $relativePath) {
    ...EventParts
  }
}
