fragment GlobalParts on Global {
  siteUrl
  gtmId
  favicon
  desktopWidth
  backgroundColor
  rule
  colors {
    __typename
    primary
    accent1
    accent2
    accent3
    accent4
    white
    grayLight
    gray
    grayDark
    black
  }
  fonts {
    __typename
    font1
    font2
    font3
    font4
  }
  sizeLeading {
    __typename
    textXs
    textSm
    textMd
    textLg
    textXl
    text2xl
    text3xl
    text4xl
    text5xl
    text6xl
    text7xl
    text8xl
  }
  buttons {
    __typename
    primaryRule
    primaryFill
    primaryBorder
    primaryTypography
    primaryPadding
    primaryRounded
    secondaryRule
    secondaryFill
    secondaryBorder
    secondaryTypography
    secondaryPadding
    secondaryRounded
    minorRule
    minorFill
    minorBorder
    minorTypography
    minorPadding
    minorRounded
  }
  links {
    __typename
    color
  }
  logo {
    __typename
    logoType
    logoTypeStyle
    image
    imageWidth
    imageHeight
    imageMargin
  }
  nav {
    __typename
    navItems {
      __typename
      label
      link
      subNavItems {
        __typename
        label
        link
      }
    }
    navAlignment
    navTypeStyle
    navBackgroundColor
    padding
  }
  rule2
  blocks {
    __typename
    ... on GlobalBlocksFeature {
      style {
        __typename
        alignment
        padding
        featureImage
        featureContent
        typographyTitle
        labelStyles
        headlineStyles
        subheadStyles
        textStyles
        contentOrder
      }
      background {
        __typename
        fillStyles
        src
        position
        ornaments {
          __typename
          src
          alignment
          width
          height
          xOffset
          yOffset
        }
      }
      image {
        __typename
        src
        alt
      }
      rule
      label
      headline
      subhead
      body
      buttons {
        __typename
        label
        link
        type
      }
      rule2
      navigationLabel
    }
    ... on GlobalBlocksPhotoCards {
      style {
        __typename
        textAlignment
        minHeight
        padding
        contentWidth
        columns
        typographyTitle
        labelStyles
        headlineStyles
        subheadStyles
        textStyles
        contentOrder
      }
      cardStyle {
        __typename
        fillStyles
        padding
        borderStyles
        imageStyles
        typographyTitle
        labelStyles
        headlineStyles
        subheadStyles
        textStyles
        buttonTitle
        buttonType
      }
      background {
        __typename
        fillStyles
        src
        position
        ornaments {
          __typename
          src
          alignment
          width
          height
          xOffset
          yOffset
        }
      }
      label
      headline
      subhead
      body
      buttons {
        __typename
        label
        link
        type
      }
      items {
        __typename
        image {
          __typename
          src
          alt
        }
        label
        headline
        subhead
        text
        link
        buttonLabel
      }
      navigationLabel
    }
    ... on GlobalBlocksTextCards {
      style {
        __typename
        textAlignment
        minHeight
        padding
        contentWidth
        columns
        typographyTitle
        labelStyles
        headlineStyles
        subheadStyles
        textStyles
        contentOrder
      }
      cardStyle {
        __typename
        fillStyles
        padding
        borderStyles
        typographyTitle
        labelStyles
        headlineStyles
        subheadStyles
        textStyles
        buttonTitle
        buttonType
      }
      background {
        __typename
        fillStyles
        src
        position
        ornaments {
          __typename
          src
          alignment
          width
          height
          xOffset
          yOffset
        }
      }
      label
      headline
      subhead
      body
      buttons {
        __typename
        label
        link
        type
      }
      items {
        __typename
        headline
        subhead
        text
        link
        buttonLabel
      }
      navigationLabel
    }
    ... on GlobalBlocksBanner {
      style {
        __typename
        textAlignment
        minHeight
        padding
        width
        typographyTitle
        labelStyles
        headlineStyles
        subheadStyles
        textStyles
        contentOrder
      }
      background {
        __typename
        fillStyles
        src
        position
        ornaments {
          __typename
          src
          alignment
          width
          height
          xOffset
          yOffset
        }
      }
      image {
        __typename
        src
        alt
      }
      label
      headline
      subhead
      body
      buttons {
        __typename
        label
        link
        type
      }
      navigationLabel
    }
    ... on GlobalBlocksEmbed {
      style {
        __typename
        minHeight
        fullWidth
        padding
      }
      background {
        __typename
        fillStyles
        src
        position
        ornaments {
          __typename
          src
          alignment
          width
          height
          xOffset
          yOffset
        }
      }
      markup
      navigationLabel
    }
    ... on GlobalBlocksTailwindFeature {
      tailwind {
        __typename
        section
        wrap
        imageWrap
        image
        contentWrap
        content
        label
        headline
        subhead
        text
        buttons
        button
      }
      image {
        __typename
        src
        alt
      }
      background {
        __typename
        fillStyles
        src
        position
        ornaments {
          __typename
          src
          alignment
          width
          height
          xOffset
          yOffset
        }
      }
      rule
      label
      headline
      subhead
      body
      buttons {
        __typename
        label
        link
      }
      rule2
      navigationLabel
    }
    ... on GlobalBlocksTailwindCards {
      tailwind {
        __typename
        section
        wrap
        imageWrap
        image
        contentWrap
        content
        label
        headline
        subhead
        text
        buttons
        button
        rule
        cardWrap
        card
        cardImageWrap
        cardImage
        cardContentWrap
        cardContent
        cardLabel
        cardHeadline
        cardSubhead
        cardText
        cardButtons
        cardButton
      }
      image {
        __typename
        src
        alt
      }
      background {
        __typename
        fillStyles
        src
        position
        ornaments {
          __typename
          src
          alignment
          width
          height
          xOffset
          yOffset
        }
      }
      rule
      label
      headline
      subhead
      body
      buttons {
        __typename
        label
        link
        type
      }
      items {
        __typename
        image {
          __typename
          src
          alt
        }
        label
        headline
        subhead
        text
        link
        buttonLabel
      }
      rule2
      navigationLabel
    }
  }
  redirects {
    __typename
    from
    to
  }
}

fragment PagesParts on Pages {
  draft
  blocks {
    __typename
    ... on PagesBlocksFeature {
      style {
        __typename
        alignment
        padding
        featureImage
        featureContent
        typographyTitle
        labelStyles
        headlineStyles
        subheadStyles
        textStyles
        contentOrder
      }
      background {
        __typename
        fillStyles
        src
        position
        ornaments {
          __typename
          src
          alignment
          width
          height
          xOffset
          yOffset
        }
      }
      image {
        __typename
        src
        alt
      }
      rule
      label
      headline
      subhead
      body
      buttons {
        __typename
        label
        link
        type
      }
      rule2
      navigationLabel
    }
    ... on PagesBlocksPhotoCards {
      style {
        __typename
        textAlignment
        minHeight
        padding
        contentWidth
        columns
        typographyTitle
        labelStyles
        headlineStyles
        subheadStyles
        textStyles
        contentOrder
      }
      cardStyle {
        __typename
        fillStyles
        padding
        borderStyles
        imageStyles
        typographyTitle
        labelStyles
        headlineStyles
        subheadStyles
        textStyles
        buttonTitle
        buttonType
      }
      background {
        __typename
        fillStyles
        src
        position
        ornaments {
          __typename
          src
          alignment
          width
          height
          xOffset
          yOffset
        }
      }
      label
      headline
      subhead
      body
      buttons {
        __typename
        label
        link
        type
      }
      items {
        __typename
        image {
          __typename
          src
          alt
        }
        label
        headline
        subhead
        text
        link
        buttonLabel
      }
      navigationLabel
    }
    ... on PagesBlocksTextCards {
      style {
        __typename
        textAlignment
        minHeight
        padding
        contentWidth
        columns
        typographyTitle
        labelStyles
        headlineStyles
        subheadStyles
        textStyles
        contentOrder
      }
      cardStyle {
        __typename
        fillStyles
        padding
        borderStyles
        typographyTitle
        labelStyles
        headlineStyles
        subheadStyles
        textStyles
        buttonTitle
        buttonType
      }
      background {
        __typename
        fillStyles
        src
        position
        ornaments {
          __typename
          src
          alignment
          width
          height
          xOffset
          yOffset
        }
      }
      label
      headline
      subhead
      body
      buttons {
        __typename
        label
        link
        type
      }
      items {
        __typename
        headline
        subhead
        text
        link
        buttonLabel
      }
      navigationLabel
    }
    ... on PagesBlocksBanner {
      style {
        __typename
        textAlignment
        minHeight
        padding
        width
        typographyTitle
        labelStyles
        headlineStyles
        subheadStyles
        textStyles
        contentOrder
      }
      background {
        __typename
        fillStyles
        src
        position
        ornaments {
          __typename
          src
          alignment
          width
          height
          xOffset
          yOffset
        }
      }
      image {
        __typename
        src
        alt
      }
      label
      headline
      subhead
      body
      buttons {
        __typename
        label
        link
        type
      }
      navigationLabel
    }
    ... on PagesBlocksEmbed {
      style {
        __typename
        minHeight
        fullWidth
        padding
      }
      background {
        __typename
        fillStyles
        src
        position
        ornaments {
          __typename
          src
          alignment
          width
          height
          xOffset
          yOffset
        }
      }
      markup
      navigationLabel
    }
    ... on PagesBlocksTailwindFeature {
      tailwind {
        __typename
        section
        wrap
        imageWrap
        image
        contentWrap
        content
        label
        headline
        subhead
        text
        buttons
        button
      }
      image {
        __typename
        src
        alt
      }
      background {
        __typename
        fillStyles
        src
        position
        ornaments {
          __typename
          src
          alignment
          width
          height
          xOffset
          yOffset
        }
      }
      rule
      label
      headline
      subhead
      body
      buttons {
        __typename
        label
        link
      }
      rule2
      navigationLabel
    }
    ... on PagesBlocksTailwindCards {
      tailwind {
        __typename
        section
        wrap
        imageWrap
        image
        contentWrap
        content
        label
        headline
        subhead
        text
        buttons
        button
        rule
        cardWrap
        card
        cardImageWrap
        cardImage
        cardContentWrap
        cardContent
        cardLabel
        cardHeadline
        cardSubhead
        cardText
        cardButtons
        cardButton
      }
      image {
        __typename
        src
        alt
      }
      background {
        __typename
        fillStyles
        src
        position
        ornaments {
          __typename
          src
          alignment
          width
          height
          xOffset
          yOffset
        }
      }
      rule
      label
      headline
      subhead
      body
      buttons {
        __typename
        label
        link
        type
      }
      items {
        __typename
        image {
          __typename
          src
          alt
        }
        label
        headline
        subhead
        text
        link
        buttonLabel
      }
      rule2
      navigationLabel
    }
  }
  meta {
    __typename
    pageTitle
    pageDescription
    siteImageSrc
  }
}
