export const colorOptions: {label: string, value: string}[] = [
  { label: "Primary", value: "primary" },
  { label: "Accent 1", value: "accent1" },
  { label: "Accent 2", value: "accent2" },
  { label: "Accent 3", value: "accent3" },
  { label: "Accent 4", value: "accent4" },
  { label: "White", value: "white" },
  { label: "Gray Light", value: "grayLight" },
  { label: "Gray", value: "gray" },
  { label: "Gray Dark", value: "grayDark" },
  { label: "Black", value: "black" },
];

export const minHeightOptions: {label: string, value: string}[] = [
  { label: "none", value: "min-h-0" },
  { label: "400", value: "min-h-100" },
  { label: "480", value: "min-h-120" },
  { label: "560", value: "min-h-140" },
  { label: "640", value: "min-h-160" },
  { label: "720", value: "min-h-180" },
  { label: "800", value: "min-h-200" },
  { label: "Screen", value: "min-h-screen" },
];

export const roundedOptions: {label: string, value: string}[] = [
  { label: "0", value: "rounded-none" },
  { label: "2", value: "rounded-sm" },
  { label: "4", value: "rounded" },
  { label: "6", value: "rounded-md" },
  { label: "8", value: "rounded-lg" },
  { label: "12", value: "rounded-xl" },
  { label: "16", value: "rounded-2xl" },
  { label: "24", value: "rounded-3xl" },
  { label: "Full", value: "rounded-full" },
]

export const iconOptions: {label: string, value: string}[] = [
  { label: "Arrow Download", value: "arrow-down-to-line-solid" },
  { label: "Arrow Left", value: "arrow-left-solid" },
  { label: "Arrow Right", value: "arrow-right-solid" },
  { label: "Arrow Share", value: "arrow-up-from-bracket-solid" },
  { label: "Arrow Out", value: "arrow-up-right-from-square-solid" },
  { label: "Chevron Down", value: "chevron-down-solid" },
  { label: "Chevron Left", value: "chevron-left-solid" },
  { label: "Chevron Right", value: "chevron-right-solid" },
  { label: "Chevron Up", value: "chevron-up-solid" },
  { label: "Chevrons Left", value: "chevrons-left-solid" },
  { label: "Chevrons Right", value: "chevrons-right-solid" },
  { label: "Circle Chevron Down", value: "circle-chevron-down-solid" },
  { label: "Circle Chevron Left", value: "circle-chevron-left-solid" },
  { label: "Circle Chevron Right", value: "circle-chevron-right-solid" },
  { label: "Circle Chevron Up", value: "circle-chevron-up-solid" },
  { label: "Circle X", value: "circle-xmark-solid" },
  { label: "X", value: "x-solid" },
  { label: "Apple", value: "apple" },
  { label: "Discord", value: "discord" },
  { label: "Facebook", value: "facebook" },
  { label: "Github", value: "github" },
  { label: "Google", value: "google" },
  { label: "Instagram", value: "instagram" },
  { label: "Linkedin", value: "linkedin" },
  { label: "Slack", value: "slack" },
  { label: "TikTok", value: "tiktok" },
  { label: "Twitter", value: "twitter" },
  { label: "YouTube", value: "youtube" },
]